### ISSUE TITLE
希望可以有可以自定义随机角色的模式

### ISSUE THREAD

**Issue by Kiana1314** [MinatoAquaCrews/nonebot_plugin_randomtkk#3]

**Comment by KafCoppelia** [comment]
我没素材

**Comment by Kiana1314** [comment]
随机找其他人 不只是找唐可可的那种

**Comment by KafCoppelia** [comment]
这个更新目前在dev分支下，[v0.1.3a1](https://github.com/MinatoAquaCrews/nonebot_plugin_randomtkk/tree/dev)，你可以试试看，关于角色名称的指定在`config.py`内，不知道是否足够
